4TEForum/Controllers/ForumController.cs
using System;
using System.Web.Mvc;

namespace _4TEForum.Controllers
{
    public class ForumController : Controller
    {
        public ActionResult Visualiza(string id)
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Forum = RecuperaForum(id);
                ViewBag.Title = ViewBag.Forum.Titulo;
                return View();
            }
            else
                return RedirectToAction("Index", "Login");
        }

        public ActionResult Adiciona()
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Title = "Criação de forum";
                ViewBag.Message = ViewBag.Title;
                return View();
            }
            else
                return RedirectToAction("Index", "Login");
        }

        public ActionResult Editar(string id)
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Forum = RecuperaForum(id);
                ViewBag.Title = $"Editar \"{ViewBag.Forum.Titulo}\"";
                ViewBag.Message = ViewBag.Title;

                return View();
            }
            else
                return RedirectToAction("Index", "Login");
        }

        public ActionResult Exclui(string id)
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Forum = RecuperaForum(id);
                ViewBag.Title = "Confirmação";
                ViewBag.Message = $"Excluir o forum \"{ViewBag.Forum.Titulo}\"?";

                return View();
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public void SalvarForum()
        {
            if (Session["UsuarioLogado"] != null)
            {
                Models.Forum forum = new Models.Forum
                {
                    Titulo = Request["titulo"],
                    Conteudo = Request["conteudo"],
                    IncluidoEm = DateTime.Now,
                    IncluidoPorId = (Session["UsuarioLogado"] as Models.Usuarios).Id
                };

                forum.SalvarForum();
                Response.Redirect("/Inicio/Forum");
            }
            else
                Response.Redirect("/Login/Index");
        }

        [HttpPost]
        public void EditarForum()
        {
            if (Session["UsuarioLogado"] != null)
            {
                Models.Forum forum = new Models.Forum
                {
                    Id = RecuperaForumId(Request["id"]),
                    Titulo = Request["titulo"],
                    Conteudo = Request["conteudo"],
                    IncluidoPorId = (Session["UsuarioLogado"] as Models.Usuarios).Id,
                    IncluidoEm = DateTime.Now.ToUniversalTime(),
                    ForumResposta = 0
                };

                forum.EditarForum();
                Response.Redirect("/Inicio/Forum");
            }
            else
                Response.Redirect("/Login/Index");
        }

        [HttpPost]
        public void ExcluirForum()
        {
            if (Session["UsuarioLogado"] != null)
            {
                RecuperaForum(Request["id"]).ExcluiForum();
                Response.Redirect("/Inicio/Forum");
            }
            else
                Response.Redirect("/Login/Index");
        }

        public int RecuperaForumId(string id)
        {
            try
            {
                return Convert.ToInt32(System.Text.Encoding.UTF8.GetString(System.Convert.FromBase64String(id)));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return -1;
            }
        }

        public Models.Forum RecuperaForum(string id)
        {
            Models.Forum forum = new Models.Forum();
            forum.RecuperaForum(RecuperaForumId(id), (Session["UsuarioLogado"] as Models.Usuarios).Id);
            return forum;
        }
    }
}

4TEForum/Controllers/InicioController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace _4TEForum.Controllers
{
    public class InicioController : Controller
    {
        public ActionResult Contacto()
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Message = "Informações para contacto";
                return View();
            }
            else
                return RedirectToAction("Index", "Login");
        }

        public ActionResult Forum()
        {
            if (Session["UsuarioLogado"] != null)
            {
                ViewBag.Title = $"Bem vind@ ao Forum 4TE, {(Session["UsuarioLogado"] as Models.Usuarios).Nome.Split(' ').First()}";
                var foruns = Models.Forum.RecuperaForuns((Session["UsuarioLogado"] as Models.Usuarios).Id).OrderByDescending(c => c.IncluidoEm);
                ViewBag.Lista = foruns;
                if (foruns.Count() > 0)
                    ViewBag.Message = "Confira os tópicos postados até o momento:";
                else
                    ViewBag.Message = "Não has tópicos postados até o momento.";

                return View();
            }
            else
                return RedirectToAction("Index", "Login");
        }
    }
}

4TEForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Forum 4TE", "Forum", "Inicio", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Forum", "Forum", "Inicio")</li>
                    <li>@Html.ActionLink("Contacto", "Contacto", "Inicio")</li>
                </ul>

                @if (Session["UsuarioLogado"] != null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink($"Olá, {Session["NomeUsuario"]}", "Forum", "Inicio")</li>
                        <li>@Html.ActionLink("Sair", "Logout", "Sair")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Forum 4TE</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>